temperatures:
  - 80
pressures:
  - 30
powers:
  - 100
initial_thicknesses:
  - 1.8e-2
k: null
noise: 0.3
n: 20
data_percentage: 3
final_time: 8e5
results_csv: "../../Results/results.csv"
Area_cell: 680
decrease_type: "chemical"
n_steps: 1000
lambda_phys: 1.0
lambda_mse: 1.0
epochs: 5000
lr: 0.01
patience: 2000
lambda_boundary: 10.0
factor: 1e2
param_inference: False
m: 10
